### PR TITLE
Nix packaging for Nomad

### PR DESCRIPTION
**Pull request by m0lentum**
`release.nix` and `Makefile.release` for publishing a package for use in our Nomad exec environment at JYU. Maybe you don't want these in the public repo since they're not useful for most people, but I thought @datakurre would be interested to see them.

By the way, our Sisu integration robot is now running successfully and I'm really happy with how neat the code looks with carrot-rcc handling the boring repetitive parts :) Will definitely use this for other integrations in the future!

### CODE REVIEW

**Comment by datakurre** [comment]
@MoleTrooper Thanks. So great to hear good news.

I wonder if that glib approach also works for `dbus-glib` and `libGL` here https://github.com/datakurre/carrot-rcc/blob/main/nix/pkgs/rcc/default.nix#L17 which I added earlier to check that rcc-installed Firefox works :thinking: 

I also wonder, why I did not run into this linker issue myself :thinking: Was it that I had previously configured our build to use FHSUserEnv wrapped rcc, but now you found a way to make it work without `FHSUserEnv` (and without extra chroot inside nomad exec chroot)?

**Comment by datakurre** [comment]
Here are the two versions: bare `rcc` and `FHSUserEnv` wrapped version https://github.com/datakurre/carrot-rcc/blob/main/nix/default.nix#L21

**Comment by datakurre** [comment]
And yes, I'll merge this later. It's better to have it here connected to carrot-rcc, than in the "camunda-rcc"-project.

**Comment by m0lentum** [comment]
Oh, I didn't realize I wasn't using the FHS-wrapped version of rcc :sweat_smile: Probably the FHS environment would have come with libc/ldd and avoided this problem. It seems the linker was the only thing needed for our current robots, but maybe FHS would be more robust in case of new dependencies in the future.

**Comment by datakurre** [comment]
@MoleTrooper Just remembered that FHSUserEnv prevented mounting the maintained certificate bundles from Nomad host into Nomad job so that they are available in RCC jobs (because chroot inside chroot). So your approach is the better one. Just need to accept that the worker needs and update every now and then when new libraries need to be added.

**Comment by m0lentum** [comment]
Forgot this pull request still existed, merged some stuff that didn't belong here, and accidentally erased more commits than I meant to when I tried to revert that merge so it closed the PR :upside_down_face:

**Comment by datakurre** [comment]
Oops. I guess the changes are till somewhere to be looked into later. I still don’t know which one is better. FHSUserEnv works better with Conda packages, without better with Nomad 😅

**Comment by m0lentum** [comment]
Yeah, the changes still exist; I pushed them back to this branch after the PR got closed. I'll try reopening and see if they appear in the PR.

**Comment by m0lentum** [comment]
That worked. I'll leave this open for you to think about when you feel like it and do my future messy merges in another branch :sweat_smile:

**Comment by datakurre** [comment]
Merged in https://github.com/datakurre/carrot-rcc/pull/30

**Pull request closed without merging**
